In [3]:
import numpy as np

In [4]:
l = [1,2,3,4,5,6]

In [5]:
# numpy besicliy produce array function this is the super class function  
ar=np.array(l)

In [6]:
ar

array([1, 2, 3, 4, 5, 6])

In [7]:
# this type dimancenal array show me 
type(ar)

numpy.ndarray

In [8]:
# this function 2 dementional array 
ar2=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [9]:
#his function give me same data (numpy besicliy produce array function this is the super class function  ).
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [10]:
a=[1,2,3,4]

In [11]:
# same index 13 and 5 row 
np.asanyarray(a)

array([1, 2, 3, 4])

In [12]:
#this funnction already array function this time not convert same data give me 
b= np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4, 5, 6]])

In [14]:
#this function give me same data index like : [21]
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5, 6]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4, 5, 6])

In [17]:
# this function asing 2 types variable any kind of serche he is give me same value .
c = a

In [18]:
c

array([1, 2, 3, 4, 5, 6])

In [19]:
a

array([1, 2, 3, 4, 5, 6])

In [20]:
# this function change value array function 
c[0] =100

In [21]:
c

array([100,   2,   3,   4,   5,   6])

In [22]:
a

array([100,   2,   3,   4,   5,   6])

In [23]:
#this function is deep copy and solo copy any numpy data
d = np.copy(a)

In [24]:
d

array([100,   2,   3,   4,   5,   6])

In [25]:
a

array([100,   2,   3,   4,   5,   6])

In [26]:
#  this function work change list number 
a[1] =400

In [27]:
a

array([100, 400,   3,   4,   5,   6])

In [28]:
#this function is deep copy and solo copy not permanetely chnange 
d

array([100,   2,   3,   4,   5,   6])

In [29]:
#this function besicly show dmanstional array three time count in banary number lambda function with 
np.fromfunction(lambda i, j: i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i, j: i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
#this function basicly using from ijter function through for loop and range function  with new data produce like : int ,boolen , float any numeric data . 
itrable =(i*i for i in range (5))

In [32]:
np.fromiter(itrable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
# thsi function using any daya brack center this function with works.
np.fromstring('234 324' ,sep =' ')

array([234., 324.])

In [34]:
np.fromstring('234 ,324' ,sep =' ,')

array([234., 324.])

In [35]:
# Numpy - Data types .

In [36]:
l =[8,5,4,6,7,2]

In [37]:
ar =np.array(l)

In [38]:
ar

array([8, 5, 4, 6, 7, 2])

In [39]:
#this function fing only how many dymantional 
ar.ndim

1

In [40]:
ar2 = np.array([[4,8,5,9,4],
                [7,2,8,6,7]])

In [41]:
ar2

array([[4, 8, 5, 9, 4],
       [7, 2, 8, 6, 7]])

In [42]:
ar2.ndim

2

In [43]:
ar.size

6

In [44]:
ar2.size

10

In [45]:
ar

array([8, 5, 4, 6, 7, 2])

In [46]:
ar2

array([[4, 8, 5, 9, 4],
       [7, 2, 8, 6, 7]])

In [47]:
ar.shape

(6,)

In [48]:
# this function shape ganarate first Row [2] and second col [5].
ar2.shape

(2, 5)

In [49]:
# this function i am run one float data but output given all data convert float number 
ar11 =np.array([(1,5,7.8) ,(8,9,7.8)])

In [50]:
ar11

array([[1. , 5. , 7.8],
       [8. , 9. , 7.8]])

In [51]:
ar11.dtype

dtype('float64')

In [52]:
list(range(5))

[0, 1, 2, 3, 4]

In [53]:
# Range function only produce "int number "not float number but Numpy with posible floating number .
list(range(1.5 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [54]:
#this function with posible float number in numpy arange .
np.arange(1.5 ,5.6)

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [55]:
#This function with esey jump any kind of  data . and this data convert to list esey posible .
np.arange(1.5 ,5.6,.3)

array([1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6, 3.9, 4.2, 4.5, 4.8, 5.1,
       5.4])

In [56]:
list(np.arange(1.5 ,5.6,.3))

[1.5,
 1.8,
 2.1,
 2.4000000000000004,
 2.7,
 3.0,
 3.3000000000000003,
 3.6000000000000005,
 3.9000000000000004,
 4.2,
 4.5,
 4.800000000000001,
 5.1000000000000005,
 5.4]

In [57]:
#this function besicly produce first 1,5 this data count in 2 line and last data produce 10 times produce data .
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [58]:
# this data function produce 5 times zeros '0' .
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
#this data produce 3 Row and 5 col array function show '0'.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
##this data produce 4 Row and 5 col array function show '0'.
# this data read 3 cross 5  (notes : 3 row and 5 col )
np.zeros((4,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [61]:
# this function basicly using 1st and 2nd col * like (2*3=6) , 2 row 3 col.
np.zeros((2,3,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [62]:
# this function produce float number in list 
np.ones(4)

array([1., 1., 1., 1.])

In [63]:
# this function produce 2 row amd 3 col .float number '1.' .
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
on = np.ones((2,3,2))

In [65]:
#This function sum 5 all '1' data with 5 sum produce out put :6 
on +5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [66]:
#This function multipction 5 all '1' data with 3 'in2' produce out put :3 
on *3

array([[[3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.]]])

In [67]:
#this function show me empty array data show me this method 
np.empty((3,4))

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [68]:
#this fuction data in degnom show me '1' '1' data cross line in data '1' show me .
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
#this function work 2 and 4 with divid and give me 20 data this mathod .
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [70]:
# this function show me log data lenth 10 .
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [71]:
# this function show me log data lenth 10 . base 2 log blanck after give me data .
np.logspace(2,5,10 , base =2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [72]:
# this function with produce randam data 3 row 4 cal data .
arr=np.random.randn(3,4)

In [73]:
import pandas as pd

In [74]:
df =pd.DataFrame(arr)

In [75]:
df

0         1         2         3
0 -1.351930 -0.224650  0.718979 -0.877264
1  0.596148  1.070499  0.480609  0.574842
2 -1.251094  0.733430 -0.072105  0.891407

In [76]:
# this function with ganarate ramdom data 
# defrence random and rand fuction data mean 0 and standard davion 1 deffrent both data 
np.random.rand(3,4)

array([[0.14211396, 0.787551  , 0.3331358 , 0.2793748 ],
       [0.53643558, 0.35117189, 0.30682615, 0.21224196],
       [0.10257573, 0.84918398, 0.22851141, 0.07152111]])

In [77]:
# this data only produce integer data and convert this dataframe .
#notes :1 to 110 range difind and 3 or 4 cross data. 
pd.DataFrame(np.random.randint(1,110, (350,420))).to_csv('Random_data.csv')

In [78]:
# this data change difrent shape 
arr =np.random.rand(3,4)

In [79]:
arr

array([[0.54553775, 0.06873302, 0.18120052, 0.18602703],
       [0.63318006, 0.00395937, 0.26779342, 0.1217748 ],
       [0.65428535, 0.36913044, 0.67491328, 0.25192681]])

In [80]:
# this data change reshape with this data .
arr1 =arr.reshape(6,2)

In [81]:
arr1

array([[0.54553775, 0.06873302],
       [0.18120052, 0.18602703],
       [0.63318006, 0.00395937],
       [0.26779342, 0.1217748 ],
       [0.65428535, 0.36913044],
       [0.67491328, 0.25192681]])

In [82]:
#this function with find single data any loaction only diofind row and col index number .
arr1[1][1]

0.18602702916570257

In [83]:
#this function with fing 2 row with 5 and 2 data with last line 3 data find . this mathod .
#example [2:5] show me row  1 col 2nd row data .
arr1[2:5,1]

array([0.00395937, 0.1217748 , 0.36913044])

In [84]:
# client tell me fing only 50 data abave data fing only ?
aar2 = np.random.randint(1,100 ,(5,5))

In [85]:
aar2

array([[67,  3, 10, 24,  1],
       [ 2, 89, 17, 77, 59],
       [29, 40,  5, 92, 33],
       [51, 16, 92, 20, 34],
       [95, 28, 76, 73, 16]])

In [86]:
# this mathod with fing 50 abave data .
aar2[aar2 >50]

array([67, 89, 77, 59, 92, 51, 92, 95, 76, 73])

In [87]:
aar2

array([[67,  3, 10, 24,  1],
       [ 2, 89, 17, 77, 59],
       [29, 40,  5, 92, 33],
       [51, 16, 92, 20, 34],
       [95, 28, 76, 73, 16]])

In [88]:
# this function with salising any data find any loction .
aar2[2:4 ,[1,2]]

array([[40,  5],
       [16, 92]])

In [89]:
# this mathod with any data manycule any data with .
aar2[0][0] =600

In [90]:
aar2

array([[600,   3,  10,  24,   1],
       [  2,  89,  17,  77,  59],
       [ 29,  40,   5,  92,  33],
       [ 51,  16,  92,  20,  34],
       [ 95,  28,  76,  73,  16]])

In [91]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [92]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [1, 2, 1]])

In [93]:
arr2

array([[2, 1, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [94]:
# this function count sum 1fst and 2nd (notes :first index - 1  +2nd index -2 both sum then produce output : 3 
arr1+arr2

array([[4, 3, 2],
       [4, 4, 3],
       [2, 4, 2]])

In [95]:
arr1-arr2

array([[ 0,  1,  0],
       [ 0,  0, -1],
       [ 0,  0,  0]])

In [96]:
arr1/arr2

array([[1. , 2. , 1. ],
       [1. , 1. , 0.5],
       [1. , 1. , 1. ]])

In [97]:
#this is not metric multipation [ this si only index wise multipication ]
# col frist metric and row 2nd matric multipication .
arr1*arr2

array([[4, 2, 1],
       [4, 4, 2],
       [1, 4, 1]])

In [98]:
#this is matric multipication '@' function with .not '*' function . 
arr1@arr2

array([[9, 8, 7],
       [9, 8, 7],
       [7, 7, 6]])

In [99]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [100]:
# this numpy fuction add any number like this add value in index array .
arr1 +100

array([[102, 102, 101],
       [102, 102, 101],
       [101, 102, 101]])

In [101]:
arr1**2

array([[4, 4, 1],
       [4, 4, 1],
       [1, 4, 1]])

In [102]:
# Numpy - Broadcasting.

In [103]:
arr =np.zeros((4,4))

In [104]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [115]:
row =np.array([1,2,3,4])

In [116]:
row

array([1, 2, 3, 4])

In [117]:
# this fucnction run Broadcasting row wise data calucalte .
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [118]:
row.T

array([1, 2, 3, 4])

In [123]:
#this function rotat 360'  this function with in numpy .
col = np.array([[1,2,3,4]])

In [124]:
col

array([[1, 2, 3, 4]])

In [125]:
col

array([[1, 2, 3, 4]])

In [127]:
#this is rule with data function Broadcating function .
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [130]:
data1 =np.random.randint(1,4,(3,4))

In [131]:
data1

array([[2, 1, 3, 3],
       [2, 1, 2, 1],
       [2, 3, 3, 1]])

In [132]:
#this function with Squar rute fing 
np.sqrt(data1)

array([[1.41421356, 1.        , 1.73205081, 1.73205081],
       [1.41421356, 1.        , 1.41421356, 1.        ],
       [1.41421356, 1.73205081, 1.73205081, 1.        ]])

In [134]:
# this function with expand fing this data base.
np.exp(data1)

array([[ 7.3890561 ,  2.71828183, 20.08553692, 20.08553692],
       [ 7.3890561 ,  2.71828183,  7.3890561 ,  2.71828183],
       [ 7.3890561 , 20.08553692, 20.08553692,  2.71828183]])

In [135]:
#this function with find log 10 value find .
np.log10(data1)

array([[0.30103   , 0.        , 0.47712125, 0.47712125],
       [0.30103   , 0.        , 0.30103   , 0.        ],
       [0.30103   , 0.47712125, 0.47712125, 0.        ]])