In [1]:
#Numpy - Array Manipulation.

In [232]:
import numpy as np

In [233]:
arr =np.random.randint(1,10,(3,4))

In [234]:
#reshape array of size 12 
arr

array([[1, 2, 9, 2],
       [8, 4, 1, 5],
       [1, 7, 2, 6]])

In [235]:
arr.reshape(6,2)

array([[1, 2],
       [9, 2],
       [8, 4],
       [1, 5],
       [1, 7],
       [2, 6]])

In [236]:
arr.reshape(2,6)

array([[1, 2, 9, 2, 8, 4],
       [1, 5, 1, 7, 2, 6]])

In [237]:
#cannot reshape array of size 12 into shape (2,7)
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [238]:
arr.reshape(2,-525455)

array([[1, 2, 9, 2, 8, 4],
       [1, 5, 1, 7, 2, 6]])

In [239]:
# this function array all data tranport 'T'.
# This function mian 180' digree rotat data 
arr.T

array([[1, 8, 1],
       [2, 4, 7],
       [9, 1, 2],
       [2, 5, 6]])

In [240]:
# real data data shape.
arr

array([[1, 2, 9, 2],
       [8, 4, 1, 5],
       [1, 7, 2, 6]])

In [241]:
# this function do any data convert single dymantion .
arr.flatten()

array([1, 2, 9, 2, 8, 4, 1, 5, 1, 7, 2, 6])

In [242]:
arr1=np.array([6, 6, 4, 5, 3, 7])

In [243]:
#This function dymantion 1 this time 
arr1.ndim

1

In [244]:
#This function with single dymantion change = 2 dymantion 
db1=np.expand_dims(arr1,axis=1)

In [245]:
db1

array([[6],
       [6],
       [4],
       [5],
       [3],
       [7]])

In [246]:
db1.ndim

2

In [247]:
np.expand_dims(arr1,axis=0)

array([[6, 6, 4, 5, 3, 7]])

In [248]:
arr

array([[1, 2, 9, 2],
       [8, 4, 1, 5],
       [1, 7, 2, 6]])

In [249]:
data =np.array([[1],[2],[3],[4]])

In [250]:
data

array([[1],
       [2],
       [3],
       [4]])

In [251]:
# this function with all difrent shape  data all data squeeze  single line output.
np.squeeze(data)

array([1, 2, 3, 4])

In [252]:
#this function with i am give 3 times data he is repeat all data 
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 9, 9, 9, 2, 2, 2, 8, 8, 8, 4, 4, 4, 1, 1, 1, 5,
       5, 5, 1, 1, 1, 7, 7, 7, 2, 2, 2, 6, 6, 6])

In [253]:
#this is Origenal data .
arr

array([[1, 2, 9, 2],
       [8, 4, 1, 5],
       [1, 7, 2, 6]])

In [254]:
# this function with working shift working this time i am give number 2 
# this function besicly rorat 2  function data 
np.roll(arr ,2)

array([[2, 6, 1, 2],
       [9, 2, 8, 4],
       [1, 5, 1, 7]])

In [255]:
# this function all array data diag shape show [6,6,4,5,3,7] this value .
np.diag(arr1)

array([[6, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 7]])

In [256]:
# Numpy - Binary Operators :

In [257]:
arr11=np.random.randint(1,10,(3,4))

In [258]:
arr10=np.random.randint(1,10,(3,4))

In [259]:
arr11

array([[2, 8, 3, 2],
       [5, 7, 9, 1],
       [9, 6, 1, 9]])

In [260]:
arr10

array([[2, 7, 4, 2],
       [8, 6, 4, 8],
       [7, 4, 3, 6]])

In [261]:
# this function data index number count one by one like '9+8=17'.
arr11+arr10

array([[ 4, 15,  7,  4],
       [13, 13, 13,  9],
       [16, 10,  4, 15]])

In [262]:
arr11*arr10

array([[ 4, 56, 12,  4],
       [40, 42, 36,  8],
       [63, 24,  3, 54]])

In [263]:
arr11/arr10

array([[1.        , 1.14285714, 0.75      , 1.        ],
       [0.625     , 1.16666667, 2.25      , 0.125     ],
       [1.28571429, 1.5       , 0.33333333, 1.5       ]])

In [264]:
#this function reminder function divid and after shase show me 9/8 =1
arr11%arr10

array([[0, 1, 3, 0],
       [5, 1, 1, 1],
       [2, 2, 1, 3]])

In [265]:
#this function nigate function 
~arr11

array([[ -3,  -9,  -4,  -3],
       [ -6,  -8, -10,  -2],
       [-10,  -7,  -2, -10]])

In [266]:
arr11>arr10

array([[False,  True, False, False],
       [False,  True,  True, False],
       [ True,  True, False,  True]])

In [267]:
#Numpy - String Function .

In [268]:
arr=np.array(['durgesh' ,'kharwar'])

In [269]:
arr

array(['durgesh', 'kharwar'], dtype='<U7')

In [270]:
#this function with upper in numpy data .
np.char.upper(arr)

array(['DURGESH', 'KHARWAR'], dtype='<U7')

In [271]:
#this function with title in numpy data .
np.char.title(arr)

array(['Durgesh', 'Kharwar'], dtype='<U7')

In [272]:
np.char.capitalize(arr)

array(['Durgesh', 'Kharwar'], dtype='<U7')

In [273]:
# Numpy - Mathmatical Functions.

In [274]:
arr1

array([6, 6, 4, 5, 3, 7])

In [275]:
np.sin(arr1)

array([-0.2794155 , -0.2794155 , -0.7568025 , -0.95892427,  0.14112001,
        0.6569866 ])

In [276]:
np.cos(arr1)

array([ 0.96017029,  0.96017029, -0.65364362,  0.28366219, -0.9899925 ,
        0.75390225])

In [277]:
np.tan(arr1)

array([-0.29100619, -0.29100619,  1.15782128, -3.38051501, -0.14254654,
        0.87144798])

In [278]:
np.tanh(arr1)

array([0.99998771, 0.99998771, 0.9993293 , 0.9999092 , 0.99505475,
       0.99999834])

In [279]:
np.log10(arr1)

array([0.77815125, 0.77815125, 0.60205999, 0.69897   , 0.47712125,
       0.84509804])

In [280]:
np.exp(arr1)

array([ 403.42879349,  403.42879349,   54.59815003,  148.4131591 ,
         20.08553692, 1096.63315843])

In [281]:
np.sqrt(arr1)

array([2.44948974, 2.44948974, 2.        , 2.23606798, 1.73205081,
       2.64575131])

In [282]:
#np.power(*args, **kwargs)
#Raise each base in `x1` to the positionally-corresponding power in `x2`.  `x1` and `x2` must be broadcastable to the same shape
np.power(arr1, 2)

array([36, 36, 16, 25,  9, 49])

In [283]:
np.mean(arr1)

5.166666666666667

In [284]:
np.median(arr1)

5.5

In [285]:
np.std(arr1)

1.3437096247164249

In [286]:
np.var(arr1)

1.8055555555555554

In [287]:
np.max(arr1)

7

In [288]:
#Short , Searching & Counting Function .

In [289]:
st= np.array([4,5,2,4,5,6,8,7,8])

In [290]:
#this functiong working all number serise wise put like  -1,2,3,4,5,6,7,8,9 ect.
np.sort(st)

array([2, 4, 4, 5, 5, 6, 7, 8, 8])

In [291]:
np.searchsorted(st,12)

9

In [292]:
sst =np.array([0,587,526,421,121,0,420,0,514,2,0,0,0])

In [293]:
sst

array([  0, 587, 526, 421, 121,   0, 420,   0, 514,   2,   0,   0,   0])

In [294]:
# this function count how many time run data count '0' 
np.count_nonzero(sst)

7

In [295]:
st

array([4, 5, 2, 4, 5, 6, 8, 7, 8])

In [296]:
# this function with fing index data  whare my data location .
np.where(st>6)

(array([6, 7, 8]),)

In [297]:
# this function with 3 abeve all data give me output.
np.extract(st>3,st)

array([4, 5, 4, 5, 6, 8, 7, 8])

In [298]:
st

array([4, 5, 2, 4, 5, 6, 8, 7, 8])

In [299]:
#Numpy - Byte Swapping .

In [300]:
st

array([4, 5, 2, 4, 5, 6, 8, 7, 8])

In [301]:
# this data give me output byte array data.
st.byteswap()

array([288230376151711744, 360287970189639680, 144115188075855872,
       288230376151711744, 360287970189639680, 432345564227567616,
       576460752303423488, 504403158265495552, 576460752303423488])

In [302]:
#Numpy - Copies & Views.

In [304]:
st

array([4, 5, 2, 4, 5, 6, 8, 7, 8])

In [305]:
#this data deep copy not change another data data change only select veriable data .
a =np.copy(st)

In [306]:
a

array([4, 5, 2, 4, 5, 6, 8, 7, 8])

In [309]:
b =st.view()

In [310]:
b

array([4, 5, 2, 4, 5, 6, 8, 7, 8])

In [311]:
b [0] =10

In [312]:
b

array([10,  5,  2,  4,  5,  6,  8,  7,  8])

In [313]:
# Numpy - Matrix Library.

In [314]:
import numpy.matlib as nm

In [316]:
#This library ganarate data  
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [318]:
# this function with by difult ganarete data "1." matrix data 
nm.ones(())

matrix([[1.]])

In [321]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [322]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [323]:
# Numpy - Linear Algebra

In [325]:
la =np.random.randint([[1,2] ,[4,5]])

In [326]:
la2 =np.random.randint([[4,2] ,[9,8]])

In [327]:
np.dot(la,la2)

array([[ 6,  1],
       [24,  4]])

In [328]:
la@la2

array([[ 6,  1],
       [24,  4]])